import App from '~/scripts/App'
import KeyItemType from '~/modules/enums/KeyItemType'
import GymBadgeRequirement from '~/scripts/achievements/GymBadgeRequirement'
import OneFromManyRequirement from '~/scripts/achievements/OneFromManyRequirement'
import ClearDungeonRequirement from '~/scripts/achievements/ClearDungeonRequirement'
import MultiRequirement from '~/scripts/achievements/MultiRequirement'
import RouteKillRequirement from '~/scripts/achievements/RouteKillRequirement'
import BadgeEnums from '~/modules/enums/Badges'
import * as GameConstants from '~/scripts/GameConstants'
import type { Gym } from '~/scripts/gym/Gym'
import { GymPokemon } from '~/scripts/gym/GymPokemon'
import { Champion } from '~/scripts/gym/Champion'
export const GymList: Record<string, Gym> = {}
