// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/vue-next/pull/3399

declare module 'vue' {
  export interface GlobalComponents {
    BattleList: typeof import('./components/pokemon/BattleList.vue')['default']
    Counter: typeof import('./components/Counter.vue')['default']
    DungeonMap: typeof import('./components/DungeonMap.vue')['default']
    DungeonView: typeof import('./components/DungeonView.vue')['default']
    Enemy: typeof import('./components/pokemon/Enemy.vue')['default']
    Footer: typeof import('./components/Footer.vue')['default']
    GymView: typeof import('./components/GymView.vue')['default']
    HallOfFame: typeof import('./components/HallOfFame.vue')['default']
    KantoSVG: typeof import('./components/map/Kanto/KantoSVG.vue')['default']
    MapDungeon: typeof import('./components/map/Kanto/mapDungeon.vue')['default']
    MapOverlay: typeof import('./components/map/Kanto/mapOverlay.vue')['default']
    MapPOI: typeof import('./components/map/Kanto/mapPOI.vue')['default']
    MapRoute: typeof import('./components/map/Kanto/mapRoute.vue')['default']
    MapTown: typeof import('./components/map/Kanto/mapTown.vue')['default']
    Notification: typeof import('./components/Notification.vue')['default']
    PickStarterTutorialModal: typeof import('./components/PickStarterTutorialModal.vue')['default']
    README: typeof import('./components/README.md')['default']
    ReceiveGymBadge: typeof import('./components/ReceiveGymBadge.vue')['default']
    ShopModal: typeof import('./components/map/ShopModal.vue')['default']
    StarterCaught: typeof import('./components/StarterCaught.vue')['default']
    StartSequence: typeof import('./components/StartSequence.vue')['default']
    TownView: typeof import('./components/map/TownView.vue')['default']
  }
}

export { }
